baseURL = "https://ksouvik52.github.io/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Souvik Kundu Research Website"
theme = "anatole"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true
publishDir = '.'

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "Souvik Kundu"
author = "Souvik Kundu"
description = "Final year PhD student, Ming Hsieh Department of Electrical and Computer Engineering, University of Southern California, USA"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
customCss = []
customJs = []
mainSections = ["post"] 
images = ["images/site-feature-image.png"]
# Google Site Verification
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/souvik-kundu-64922b50/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/ksouvik52"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/souvik.kundu1"

[[params.socialIcons]]
icon = "ai ai-google-scholar"
title = "Google Scholar"
url = "https://scholar.google.com/citations?user=b591SVkAAAAJ"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://twitter.com/skundu52"

[[params.socialIcons]]
icon = "fas fa-file-pdf"
title = "Resume"
url = "/files/resume.pdf"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "E-mail"
url = "mailto:souvikku@usc.edu"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  weight = 50
  identifier = "about"
  url = "/home/"

  [[menu.main]]
  name = "Projects"
  weight = 55
  identifier = "projects"
  url = "/projects/"

  [[menu.main]]
  name = "Publications"
  weight = 65
  identifier = "publications"
  url = "/publication/"

  [[menu.main]]
  name = "Talks"
  weight = 80
  identifier = "talks"
  url = "/talks/"